services:
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    container_name: parkman_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/parkman
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    restart: always
    depends_on:
      - app
  app:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    container_name: parkman
    volumes:
      - .:/var/www/parkman
